[package]
name = "hello"
version = "0.1.0"
authors = ["tunc kiral <tunc.kiral@gmail.com>"]
edition = "2018"
run= "default-run"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
